server:
  port: 9903
spring:
  application:
    name: czs-gateway
  #redis配置
  redis:
    database: 0
    host: 119.29.53.220   # 腾讯云
    # host: 47.100.202.151    # 阿里云
    port: 6379
    password: czsredispwd
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  # 数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.53.220:13306/czs?characterEncoding=utf8&useSSL=false
    username: root
    password: root_123
    MaxActive: 30
    minIdle: 5
    maxWait: 10000
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9901/eureka
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: 47.100.202.151:${server.port}
#访问地址映射，即将所有的服务（server-id）全部替换替换为czs应用的
#例如：
#   原先访问地址为：http://localhost:9904/czs-manage/book/search
#   映射后访问地址：http://localhost:9903/czs/m/book/search
zuul:
  routes:
    czs-manage-process: /czs/mp/**
    czs-manage: /czs/m/**
    czs-admin: /czs/admin/**
  #屏蔽原先服务入口
  #ignored-patterns: /czs-*/**
  #处理请求头为空的的问题（主要解决cookie问题）
  sensitive-headers:
  #超时时间（触发熔断机制）
  host:
    socket-timeout-millis: 6000
    connect-timeout-millis: 6000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000  # 熔断超时时长：6000ms
ribbon:
  ReadTimeout: 60000      # ribbon读取超时时长
  ConnectTimeout: 60000   # ribbon链接超时时长
