server:
  port: 9904
  servlet:
    session:
      timeout: 10
    #context-path: /manage
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: czs-manage
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  #redis配置
  redis:
    database: 0
    # host: 119.29.53.220   # 腾讯云
    host: 47.100.202.151    # 阿里云
    port: 6379
    # password: beasts
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 1000
  #druid配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.29.53.220:13306/czs?characterEncoding=utf8&useSSL=false
    username: root
    password: root_123
    MaxActive: 30
    minIdle: 5
    maxWait: 10000
    validationQuery: SELECT 'x'
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
logging:
  level:
    com:
      beasts:
        manager: debug
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:9901/eureka
  instance:
    prefer-ip-address: true
    #instance-id: ${spring.cloud.client.ip-address}:${server.port}
    instance-id: 47.100.202.151:${server.port}